// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftwuxkrkczwlvnmdsfpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0d3V4a3JrY3p3bHZubWRzZnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDUyMzgsImV4cCI6MjA1Nzk4MTIzOH0.rrR_7lYUYe2TJwcvWkRVw0yy4O7XPfg3EFsu9DlUlIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);